package cases

/**
 * @author Artur Bosch
 */
class Exceptions {

	fun main() {
		try {

		} catch (e: ArrayIndexOutOfBoundsException) {

		} catch (e: Error) {

		} catch (e: Exception) {

		} catch (e: IndexOutOfBoundsException) {

		} catch (e: RuntimeException) {

		} catch (e: NullPointerException) {

		}
	}

}